#path to basespace files
input_data: "/data/gpfs/assoc/inbre/projects/melinda_yerka/sorghum_data/gbs_ssr_progeny_data/ssr_data"
ref: "/data/gpfs/assoc/inbre/projects/common_references/Sbicolor_v5.1_fromPhytozome/Sbicolor_730_v5.0.fa"
regions: "/data/gpfs/assoc/inbre/projects/melinda_yerka/sorghum_data/gbs_ssr_progeny_data/HipSTR-references/sbicolorv5/SBIv5.hipstr_reference.bed"

##Can be either a number or a comma seperated list of values
#minreads: "10"
minreads: "10,25,100,150"
hipstr_exec: "/data/gpfs/home/hvasquezgross/hipstr_singularity/hipstr_latest.sif"
